### ISSUE TITLE
Robot Prototype

### ISSUE THREAD

**Issue by tomlazar** [2202Programming/Eryx#22]
We need the mechanical team to finish the robot

**Comment by aaron97neu** [comment]
Typical detailed issue. Thanks

Details on mechanical side of the robot:

-Have been having problems with the shooter and the new machined parts, but that is being worked on as I type. ETA Monday Night
                **-Programmer requirements**\- Motor control for 4 sparks with and without encoders (w/out- full speed), option to only run on two motors, and a "burp" that will spit the ball out a low speed for low goal. Elevation control will be a single dual-action pneumatic piston with "High" (~60) and "Low" (~40) positions. Will need to be lowered for low bar traversal

-Intake should be done by end of the day sat
                **-Programmer requirements**\- single motor, single speed, bidirectional. Talk to Ana for more detail

-Trigger should be done by end of day sat. Looser ETA, not many people working on it. 
                **-Programmer requirements**\-  single dual-action pneumatic piston that will quickly shove the ball into the shooter and then immediately return

-Chassis and electrical- done (prototype)

All of above is prototype bot. Production has been started but is not much more than a few nanotubes. Mech leads are in high gear (Quick but careless). We will get stuff done as long as the grunts do not get in our way. Planning on every night next week.

**Comment by tomlazar** [comment]
- [ ] **Shooter:** We need to have some simple code to create all these sparks @payalahuja98 could you work on this
- [ ] **Intake:** Simple will mock something up
- [x] **Chassis** and Electrical
- [ ] **Trigger:** Simple piston that will be contained in the shooter class
